add_newline = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_status]
style = "bold yellow"
conflicted = "="
untracked = "?"
modified = "~"
staged = "+"
deleted = "-"
renamed = "»"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✘"

[cmd_duration]
min_time = 2000
format = "[$duration](bold yellow) "
