#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top \
    height=30 \
    blur_radius=30 \
    color=$BAR_COLOR \
    sticky=off \
    padding_left=10 \
    padding_right=10 \

default=(
    updates=when_shown
    
    padding_left=5
    padding_right=5

    background.color=$ITEM_BG_COLOR 
    background.corner_radius=5
    background.height=20

    icon.font="Hack Nerd Font:Semibold:15.0"
    icon.color=$WHITE
    icon.padding_left=10
    icon.padding_right=4

    label.font="Hack Nerd Font:Semibold:15.0"
    label.color=$WHITE
    label.padding_left=10
    label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add item front_app left \
    --set front_app background.color=$ACCENT_COLOR \
                    icon.color=$BAR_COLOR \
                    icon.font="sketchybar-app-font:Regular:16.0" \
                    label.color=$BAR_COLOR \
                    script="$PLUGIN_DIR/front_app.sh" \
    --subscribe front_app front_app_switched

# -- Aerospace compatibility --
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=$ACCENT_COLOR \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        icon="" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# -- Right Items --
sketchybar --add item clock right \
    --set clock \
    icon=􀐫 \
    label="$(date +'%H:%M:%S')" \
    update_freq=1 \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item calendar right \
    --set calendar \
    icon=􀉉 \
    label="$(date +'%a %d %b')" \
    update_freq=60 \
    --subscribe calendar system_woke

sketchybar --add item battery right \
           --set battery update_freq=120 \
                         script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

sketchybar --add item volume right \
    --set volume \
    icon=􀊠 \
    script="$PLUGIN_DIR/volume.sh" \
    update_freq=1 \
    --subscribe volume volume_change

sketchybar --add item cpu right \
    --set cpu \
    icon=􀫥\
    update_freq=2 \
    script="$PLUGIN_DIR/cpu.sh" \

sketchybar  --add item memory right \
            --set   memory \
                    icon=􀫦\
                    update_freq=2 \
                    script="$PLUGIN_DIR/memory.sh" \

sketchybar  --add item network right \
            --set   network \
                    icon=􀙇\
                    update_freq=1 \
                    script="$PLUGIN_DIR/network.sh" \

# -- Center Items --

sketchybar --update
