#!/bin/zsh

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top \
    height=20 \
    blur_radius=30 \
    color=$BAR_COLOR \
    sticky=off \
    padding_left=10 \
    padding_right=10 \

default=(
    updates=when_shown
    
    padding_left=5
    padding_right=5

    background.color=$ITEM_BG_COLOR 
    background.corner_radius=5
    background.height=20

    icon.font="SF Pro:Semibold:15.0"
    icon.color=$WHITE
    icon.padding_left=10
    icon.padding_right=4

    label.font="SF Pro:Semibold:15.0"
    label.color=$WHITE
    label.padding_left=10
    label.padding_right=4
)
sketchybar --default "${default[@]}"

#### Aerospace compatibility
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# -- Right Items --
sketchybar --add item clock right \
    --set clock \
    icon=􀐫 \
    label="$(date +'%H:%M:%S')" \
    update_freq=1 \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item calendar right \
    --set calendar \
    icon=􀉉 \
    label="$(date +'%a %d %b')" \

sketchybar --add item volume right \
    --set volume \
    icon=􀊠 \
    script="$PLUGIN_DIR/volume.sh" \
    update_freq=1 \
    --subscribe volume volume_change

# ##### Adding Left Items #####
# # We add some regular items to the left side of the bar, where
# # only the properties deviating from the current defaults need to be set
#
# sketchybar --add item chevron left \
#            --set chevron icon= label.drawing=off \
#            --add item front_app left \
#            --set front_app icon.drawing=on script="$PLUGIN_DIR/front_app.sh" \
#            --subscribe front_app front_app_switched
#
# ##### Adding Right Items #####
# # In the same way as the left items we can add items to the right side.
# # Additional position (e.g. center) are available, see:
# # https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
#
# # Some items refresh on a fixed cycle, e.g. the clock runs its script once
# # every 10s. Other items respond to events they subscribe to, e.g. the
# # volume.sh script is only executed once an actual change in system audio
# # volume is registered. More info about the event system can be found here:
# # https://felixkratz.github.io/SketchyBar/config/events
#
# sketchybar --add item clock right \
#            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
