export ZSH="$HOME/.oh-my-zsh"
export ANDROID_HOME="$HOME/Library/Android/sdk"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home"
export NVM_DIR="$HOME/.nvm"
export OPENROUTER_API_KEY="$(security find-generic-password -ws 'openrouter-api-key' 2>/dev/null)"
export GEMINI_API_KEY="$(security find-generic-password -ws 'gemini-api-key' 2>/dev/null)"
